name: Agent-Powered Workflows 
description: |
  This AMP demonstrates an Agentic workflow application which uses a variety of existing tools and agents to help users traverse varied and difficult problems
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2024-09-28"

environment_variables:
  AWS_ACCESS_KEY_ID:
    default: "aws_key"
    description: >-
      AWS Key ID. Check the Amazon Bedrock documentation for information about role access
  AWS_SECRET_ACCESS_KEY:
    default: "aws_secret_key"
    description: >-
      AWS Secret Key
  AWS_DEFAULT_REGION:
    default: "us-west-2"
    description: >-
      AWS region

runtimes:
  - editor: PBJ Workbench
    kernel: Python 3.10
    edition: Standard

tasks:
  - type: run_session
    name: Install Dependencies
    script: amp_1_session-install-deps/install-requirements.py
    short_summary: Install Dependencies
    kernel: python3
    cpu: 2
    memory: 4

    - type: start_application
    name: Sample Agent Application - Case Summarizer
    subdomain: case-summarizer
    script: sample_external_applications/case_summarizer_app/case_summarizer_app.py
    long_summary: Launching a case summarization app to be used by the Agentic workflow application 
    cpu: 2
    memory: 8
    environment_variables:
      TASK_TYPE: START_APPLICATION