name: Agent-Powered Workflows 
description: |
  This AMP demonstrates an Agentic workflow application which uses a variety of existing tools and agents to help users traverse varied and difficult problems
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2024-09-28"

environment_variables:
  AWS_ACCESS_KEY_ID:
    default: "aws_key"
    description: >-
      AWS Key ID. Check the Amazon Bedrock documentation for information about role access
  AWS_SECRET_ACCESS_KEY:
    default: "aws_secret_key"
    description: >-
      AWS Secret Key
  AWS_DEFAULT_REGION:
    default: "us-west-2"
    description: >-
      AWS region

runtimes:
  - editor: PBJ Workbench
    kernel: Python 3.10
    edition: Standard

tasks:
  - type: run_session
    name: Install Dependencies
    script: amp_1_session-install-deps/install-requirements.py
    short_summary: Install Dependencies
    kernel: python3
    cpu: 2
    memory: 4

  - type: create_model
    name: Case Summarizer Backend
    entity_label: case_summarizer_backend
    description: This sample model API endpoint is used to generate support ticket intent
    short_summary: Create the sample support ticket intent model api endpoint
    access_key_environment_variable: CASE_SUMMARIZER_ACCESS_KEY
    default_resources:
      cpu: 2
      memory: 4
      gpu: 0
    default_replication_policy:
      type: fixed
      num_replicas: 1

  - type: build_model
    name: Build Case Summarizer Backend
    short_summary: Build Case Summarizer Backend
    entity_label: case_summarizer_backend
    comment: Build Case Summarizer Backend
    examples:
      - request:
          case_id: "981492"
        response: ""
    target_file_path: sample_external_applications/case_summarizer_app/agent-backend/case_summarizer_backend.py
    target_function_name: summarize_case

  - type: deploy_model
    name: case_summarizer_backend
    short_summary: Deploy Case Summarizer Backend
    entity_label: case_summarizer_backend
    cpu: 2
    memory: 4
    gpu: 0
  

  - type: start_application
    name: Sample Agent Application UI - Case Summarizer
    subdomain: case-summarizer
    script: sample_external_applications/case_summarizer_app/case_summarizer_app.py
    long_summary: Launching a case summarization app to be used by the Agentic workflow application 
    cpu: 2
    memory: 8
    environment_variables:
      TASK_TYPE: START_APPLICATION