name: Agent-Powered Workflows 
description: |
  This AMP demonstrates an Agentic workflow application which uses a variety of existing tools and agents to help users traverse varied and difficult problems
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2024-09-28"

environment_variables:
  AWS_ACCESS_KEY_ID:
    default: "aws_key"
    description: >-
      AWS Key ID. Check the Amazon Bedrock documentation for information about role access
  AWS_SECRET_ACCESS_KEY:
    default: "aws_secret_key"
    description: >-
      AWS Secret Key
  AWS_DEFAULT_REGION:
    default: "us-west-2"
    description: >-
      AWS region
  AWS_BEDROCK_MODEL:
    default: "anthropic.claude-3-sonnet-20240229-v1:0"
    description: >-
      AWS Bedrock model ID

runtimes:
  - editor: PBJ Workbench
    kernel: Python 3.10
    edition: Standard

tasks:
  - type: run_session
    name: Install Dependencies
    script: amp_1_session-install-deps/install-requirements.py
    short_summary: Install Dependencies
    kernel: python3
    cpu: 1
    memory: 4

  - type: create_model
    name: Case Summarizer Backend
    entity_label: case_summarizer_backend
    description: This sample external application backend is used to generate support case summaries
    short_summary: Create the Case Summarizer Backend endpoint
    access_key_environment_variable: CASE_SUMMARIZER_ACCESS_KEY
    default_resources:
      cpu: 1
      memory: 4
      gpu: 0
    default_replication_policy:
      type: fixed
      num_replicas: 1

  - type: build_model
    name: Build Case Summarizer Backend
    short_summary: Build Case Summarizer Backend
    entity_label: case_summarizer_backend
    comment: Build Case Summarizer Backend
    examples:
      - request:
          case_id: "981492"
        response: ""
    target_file_path: sample_external_applications/case_summarizer_app/agent-backend/case_summarizer_backend.py
    target_function_name: summarize_case

  - type: deploy_model
    name: case_summarizer_backend
    short_summary: Deploy Case Summarizer Backend
    entity_label: case_summarizer_backend
    cpu: 1
    memory: 4
    gpu: 0

  - type: create_model
    name: Support Ticket Query Backend
    entity_label: ticket_query_backend
    description: This sample external application backend is used to query for recent support cases
    short_summary: Create the Ticket Query Backend endpoint
    access_key_environment_variable: TICKET_QUERY_ACCESS_KEY
    default_resources:
      cpu: 1
      memory: 4
      gpu: 0
    default_replication_policy:
      type: fixed
      num_replicas: 1

  - type: build_model
    name: Build Support Ticket Query Backend
    short_summary: Build Ticket Query Backend
    entity_label: ticket_query_backend
    comment: Build Support Ticket Query Backend
    examples:
      - request:
          account: "Main Street Bank"
        response: ""
    target_file_path: sample_external_applications/recent_support_tickets_query_app/agent_backend/support_tickets_query_backend.py
    target_function_name: find_support_cases

  - type: deploy_model
    name: ticket_query_backend
    short_summary: Deploy Support Ticket Query Backend
    entity_label: ticket_query_backend
    cpu: 1
    memory: 4
    gpu: 0

  - type: create_model
    name: Usage Consumption Trends Backend
    entity_label: usage_consumption_backend
    description: This sample external application backend is used to get recent customer consumption changes
    short_summary: Create the Usage Consumption Trends Backend endpoint
    access_key_environment_variable: USAGE_CONSUMPTION_ACCESS_KEY
    default_resources:
      cpu: 1
      memory: 4
      gpu: 0
    default_replication_policy:
      type: fixed
      num_replicas: 1

  - type: build_model
    name: Usage Consumption Trends Backend
    short_summary: Usage Consumption Trends Backend
    entity_label: usage_consumption_backend
    comment: Usage Consumption Trends Backend
    examples:
      - request:
          prduct: "Cloduera Machine Learning"
        response: ""
    target_file_path: sample_external_applications/usage_consumption_query_app/agent_backend/usage_consumption_query_backend.py
    target_function_name: get_consumption_trends

  - type: deploy_model
    name: usage_consumption_backend
    short_summary: Deploy Usage Consumption Trends Backend
    entity_label: usage_consumption_backend
    cpu: 1
    memory: 4
    gpu: 0

  - type: start_application
    name: Sample Agent Application UI - Usage Consumption
    subdomain: usage-consumption
    script: sample_external_applications/usage_consumption_query_app/agent_app/usage_consumption_query_app.py
    long_summary: Launching a case summarization app to be used by the Agentic workflow application 
    cpu: 1
    memory: 4
    environment_variables:
      TASK_TYPE: START_APPLICATION

  - type: start_application
    name: Sample Agent Application UI - Case Summarizer
    subdomain: case-summarizer
    script: sample_external_applications/case_summarizer_app/agent-ui/case_summarizer_app.py
    long_summary: Launching a case summarization app to be used by the Agentic workflow application 
    cpu: 1
    memory: 4
    environment_variables:
      TASK_TYPE: START_APPLICATION

  - type: start_application
    name: Sample Agent Application UI - Ticket DB Query
    subdomain: ticket-query
    script: sample_external_applications/recent_support_tickets_query_app/agent_app/support_tickets_query_app.py
    long_summary: Launching a Ticket DB Query app to be used by the Agentic workflow application 
    cpu: 1
    memory: 4
    environment_variables:
      TASK_TYPE: START_APPLICATION

  - type: start_application
    name: Sample Agent Application - Knowledge Graph
    subdomain: knowledge-graph
    script: sample_external_applications/accounts_knowledge_graph_app/app-entrypoint.py
    long_summary: Launching a knowledge graph tool to be used by the Agentic Workflow system
    cpu: 1
    memory: 4
    environment_variables:
      TASK_TYPE: START_APPLICATION

  - name: AYA Chat Application
    subdomain: aya-chat
    script: aya-chat-app.py
    long_summary: Launching main application with full agent orchestration.
    cpu: 1
    memory: 4
    environment_variables:
      TASK_TYPE: START_APPLICATION